name: Build and Test

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
  bors-gate:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: "true"
